export const STORAGE_KEY = "dualsub_settings";

export const DEFAULT_SETTINGS = Object.freeze({
  primaryLang: "en",
  secondaryLang: "zh-Hant",
  subtitleDisplayMode: "both",
  topOffsetPx: 72,
  bottomOffsetPx: 72,
  translationProvider: "youtube",
  aiModel: "gemini-2.0-flash",
  aiApiKey: "",
  aiSourceLang: "en",
  aiTargetLang: "zh-Hant",
  aiMinChars: 12,
  pocketBaseUrl: "",
  pocketBaseCollection: "translations",
  pocketBaseTimedCollection: "timed_captions",
  pocketBaseAuthCollection: "users",
  pocketBaseEmail: "",
  pocketBaseToken: "",
  pocketBaseUserId: "",
  fontSize: 24,
  lineSpacing: 1.1,
  subtitleTextColor: "#ffffff",
  subtitleBackgroundColor: "#000000",
  subtitleBackgroundOpacity: 0.35,
  subtitleFontWeight: 600,
  subtitleBorderRadiusPx: 4,
  position: "bottom",
  opacity: 0.9
});
